version: '3.8'

services:
  nginx:
    image: nginx:1.21.1
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  php:
    build: ./docker/php
    volumes:
      - ./source:/var/www/
    # mysqlのコンテナが起動した後、phpのコンテナが起動するようにする
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0.26
    # 環境変数
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: my_db
      MYSQL_USER: phper
      MYSQL_PASSWORD: password
    command:
      # 認証プラグインの変更
      mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      # PCとコンテナ内のデータを共有する
      - ./docker/db/data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    # 環境変数を設定、MySQLのコンテナで定義したユーザー名、パスワード、データベース名などを設定する
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=phper
      - PMA_PASSWORD=password
    # mysqlのコンテナが起動した後、このコンテナが起動するようにする
    depends_on:
      - mysql
    # localhost:8080でアクセスできるようにする
    ports:
      - 8080:80




# # projectディレクトリに移動
# cd project

# # コンテナを起動する。オプションの-dは、バックグラウンドで起動、--buildはDockerfileに基づき、最初からイメージをつくるということ
# docker compose up --build -d
